/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.uncc.netbeans.ros.project.ui;

import java.util.Properties;

/**
 *
 * @author arwillis
 */
public class CustomizerPanelGeneral extends javax.swing.JPanel {
    Properties properties;
    /**
     * Creates new form CustomizerPanelGeneral2
     */
    public CustomizerPanelGeneral(String projectPath, Properties properties) {
        this.properties = properties;
        initComponents();
        rosProjectPath.setText(projectPath);
        rosRootInstallPath.setText(properties.getProperty("ros.root"));
        rosWorkspaceFolder.setText(properties.getProperty("ros.ws"));
        rosBuildFolder.setText(properties.getProperty("ros.ws.build"));
        rosInstallFolder.setText(properties.getProperty("ros.ws.install"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rosProjectPath = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        rosRootInstallPath = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        rosWorkspaceFolder = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        rosInstallFolder = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        rosBuildFolder = new javax.swing.JTextArea();

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(CustomizerPanelGeneral.class, "CustomizerPanelGeneral.jLabel5.text")); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CustomizerPanelGeneral.class, "CustomizerPanelGeneral.jLabel1.text")); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CustomizerPanelGeneral.class, "CustomizerPanelGeneral.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(CustomizerPanelGeneral.class, "CustomizerPanelGeneral.jLabel3.text")); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(CustomizerPanelGeneral.class, "CustomizerPanelGeneral.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rosProjectPath, org.openide.util.NbBundle.getMessage(CustomizerPanelGeneral.class, "CustomizerPanelGeneral.rosProjectPath.text")); // NOI18N
        rosProjectPath.setPreferredSize(new java.awt.Dimension(204, 17));

        rosRootInstallPath.setColumns(20);
        rosRootInstallPath.setRows(1);
        rosRootInstallPath.setAutoscrolls(false);
        rosRootInstallPath.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rosRootInstallPathPropertyChange(evt);
            }
        });
        jScrollPane8.setViewportView(rosRootInstallPath);

        rosWorkspaceFolder.setColumns(20);
        rosWorkspaceFolder.setRows(1);
        rosWorkspaceFolder.setAutoscrolls(false);
        rosWorkspaceFolder.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rosWorkspaceFolderPropertyChange(evt);
            }
        });
        jScrollPane9.setViewportView(rosWorkspaceFolder);

        rosInstallFolder.setColumns(20);
        rosInstallFolder.setRows(1);
        rosInstallFolder.setAutoscrolls(false);
        rosInstallFolder.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rosInstallFolderPropertyChange(evt);
            }
        });
        jScrollPane10.setViewportView(rosInstallFolder);

        rosBuildFolder.setColumns(20);
        rosBuildFolder.setRows(1);
        rosBuildFolder.setAutoscrolls(false);
        rosBuildFolder.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rosBuildFolderPropertyChange(evt);
            }
        });
        jScrollPane11.setViewportView(rosBuildFolder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rosProjectPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rosProjectPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rosRootInstallPathPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rosRootInstallPathPropertyChange
        // TODO add your handling code here:
        properties.setProperty("ros.root",rosRootInstallPath.getText());
    }//GEN-LAST:event_rosRootInstallPathPropertyChange

    private void rosWorkspaceFolderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rosWorkspaceFolderPropertyChange
        // TODO add your handling code here:
        properties.setProperty("ros.ws",rosWorkspaceFolder.getText());
    }//GEN-LAST:event_rosWorkspaceFolderPropertyChange

    private void rosBuildFolderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rosBuildFolderPropertyChange
        // TODO add your handling code here:
        properties.setProperty("ros.ws.build",rosBuildFolder.getText());
    }//GEN-LAST:event_rosBuildFolderPropertyChange

    private void rosInstallFolderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rosInstallFolderPropertyChange
        // TODO add your handling code here:
        properties.setProperty("ros.ws.install",rosInstallFolder.getText());
    }//GEN-LAST:event_rosInstallFolderPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea rosBuildFolder;
    private javax.swing.JTextArea rosInstallFolder;
    private javax.swing.JLabel rosProjectPath;
    private javax.swing.JTextArea rosRootInstallPath;
    private javax.swing.JTextArea rosWorkspaceFolder;
    // End of variables declaration//GEN-END:variables
}
